# Alembic configuration file
# Purpose: Provide Alembic with instructions for automating database migrations

# The SqlAlchemy connection string. This must start with the dialect name.
sqlalchemy.url = sqlite:///./test.db

# The encoding of files.
sqlalchemy.encoding = utf-8

# logging level - default is WARN
loglevel = WARN

# logging level of Alembic's lib.logging logger
sqlalchemy_logging_level = WARN
